[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.8.1"

[profile.release]
lto = true
opt-level = 3
panic = "abort"

[profile.dev]
panic = "abort"
